### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by JosephMart** [jellyfin/jellyfin-ios#10]
I am starting to use jellyfin and as an IOS user, I would like to help contribute to this project if possible. Is the current state of the app simply an embedded browser? Is there a roadmap or list of tasks that I can help contribute towards? 😊

**Comment by dkanada** [comment]
It is indeed mostly an embedded browser with a small selection of components written locally. What languages and tools are you familiar with?

**Comment by brunsy** [comment]
Before you get into roadmaps/tasks could you write something in the docs to say how this project plans to be different from jellyfin-react-client. That project also contains Android and iOS parts.

**Comment by thornbill** [comment]
That’s a good point. I will write something for the README. This app is a wrapper for the webapp (similar to the current Android app). The goal of the React Native client is to replace the web wrappers with a truly native app.
