### ISSUE TITLE
Directly play 4k video without transcoding 

### ISSUE THREAD

**Issue by amoyzc** [jellyfin/jellyfin-ios#101]
Currently, when I play 4K video on my iPad, it will be forced to transcoding. 

Is it possible to directly play 4k video without transcoding? I noticed that my plex app allow me to do so, so iPad should be able to directly play 4k without transcoding.

**Comment by dkanada** [comment]
Can you post a screenshot of the playback information? That might help us figure out the reason.

**Comment by amoyzc** [comment]
![F907BADD-D5C9-4DF5-8DE0-9A0A4823F284](https://user-images.githubusercontent.com/10098980/86706518-d4579f80-bfcb-11ea-9b04-6bdfe620b0dd.png)
![66EBF411-513E-4228-920E-4BB560878FFC](https://user-images.githubusercontent.com/10098980/86706537-d883bd00-bfcb-11ea-817b-9d5c115db23e.png)
Sure, here is the screenshot.

**Comment by rocinante333** [comment]
Adding to this: 4K videos on my iPhone 11 are being transcoded and creating transcode logs as well.
[logfile.txt](https://github.com/jellyfin/jellyfin-expo/files/5761105/logfile.txt)

**Comment by camc314** [comment]
Try enabling fmp4 in 
user -> playback -> check `Prefer fMP4-HLS Media Container`

**Comment by thornbill** [comment]
I believe that setting is unavailable in 10.6, but will be available in 10.7 once it is released.

**Comment by camc314** [comment]
> I believe that setting is unavailable in 10.6, but will be available in 10.7 once it is released.

Ah yeah, I've been using it for so long, I forgot it wasn't in 10.6

**Comment by thornbill** [comment]
I believe this should be working with server version 10.7.
