### ISSUE TITLE
Android back button behaviour is inconsistent

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#121]
The OS level back button on Android does not trigger navigation in the webview.

**Comment by Antihero64** [comment]
`import React, { Component, useState } from "react";
import { View, Text, BackHandler } from 'react-native';
import { WebView } from 'react-native-webview';


export default class App extends Component {

constructor(props) {
    super(props);
    this.WEBVIEW_REF = React.createRef();
}

componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);
}

componentWillUnmount() {
  BackHandler.removeEventListener('hardwareBackPress', this.handleBackButton);
}

handleBackButton = ()=>{
   this.WEBVIEW_REF.current.goBack();
   return true;
}

onNavigationStateChange(navState) {
  this.setState({
    canGoBack: navState.canGoBack
  });
}

render(){
   return (
    <WebView
        source={{ uri: "https://www.example.com" }}
        ref={this.WEBVIEW_REF}
        style={{ marginTop: 20 }}
        onNavigationStateChange={this.onNavigationStateChange.bind(this)}
     />
    )

 }
}`


i used this to manage the backhandler. But i don´t get a pull to refresh in my project..

**Comment by Cryptec** [comment]
```
import React, { Component, useState } from "react";
import { View, Text, BackHandler } from 'react-native';
import { WebView } from 'react-native-webview';


export default class App extends Component {

constructor(props) {
    super(props);
    this.WEBVIEW_REF = React.createRef();
}

componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);
}

componentWillUnmount() {
  BackHandler.removeEventListener('hardwareBackPress', this.handleBackButton);
}

handleBackButton = ()=>{
   this.WEBVIEW_REF.current.goBack();
   return true;
}

onNavigationStateChange(navState) {
  this.setState({
    canGoBack: navState.canGoBack
  });
}

render(){
   return (
    <WebView
        source={{ uri: "https://www.example.com" }}
        ref={this.WEBVIEW_REF}
        style={{ marginTop: 20 }}
        onNavigationStateChange={this.onNavigationStateChange.bind(this)}
     />
    )

 }
}
```

i used this to manage the backhandler. But i don´t get a pull to refresh in my project..

**Comment by thornbill** [comment]
Thanks I will see if I can get that working at some point!

This is the approach I used to get pull to refresh working for the webview. It seems to work well for both Android and iOS in my testing in case it helps.

Reference: https://github.com/react-native-community/react-native-webview/issues/103#issuecomment-610731592

Implementation: https://github.com/jellyfin/jellyfin-expo/blob/master/components/RefreshWebView.js
