### ISSUE TITLE
Photo Sync and Gesture Support

### ISSUE THREAD

**Issue by punction** [jellyfin/jellyfin-ios#129]
很好用，希望加入1.照片同步功能。2.iOS手机客户端的手势操作功能。谢谢

> **EDIT:** Adding translation from Google Translate

Very easy to use, hope to add 1. Photo synchronization function. 2. Gesture operation function of iOS mobile client. Thank you

**Comment by thornbill** [comment]
Photo Sync was discussed by the core Jellyfin team and decided to be out of scope for the project.

If you could provide some specifics about the types of gestures that need supported, that could be possible to add though.

**Comment by thornbill** [comment]
Closing due to lack of information. Feel free to provide additional details and we can reopen. :smiley:
