### ISSUE TITLE
Remove settings migration

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#138]
The migration code for the old method of storing settings should be removed. This should make app startup slightly faster also.

https://github.com/jellyfin/jellyfin-expo/blob/master/App.js#L41

**Comment by Ayush7-BIT** [comment]
Can i work on this issue?

**Comment by thornbill** [comment]
Sure! The description above links to the relevant part of the code that should be removed. In addition to that section, the `CachingStorage` file should no longer be needed.
