### ISSUE TITLE
Use SafeAreaView for Better Screen Support

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-ios#14]
Currently when running on my iPhone X, the home indicator stays active and never goes away.

This could be an artifact of running it through Snack, but I'm not sure.

A few quick searches seems to indicate that we should implement SafeAreaView, which will help handle this accordingly. Here's a link: https://github.com/react-native-community/react-native-safe-area-view

**Comment by anthonylavado** [comment]
So this issue still persists in the release build. That said, if you fullscreen from the controls, the native video player does hide the indicator for you.

We should probably still fix this though.

**Comment by dannymichel** [comment]
> So this issue still persists in the release build. That said, if you fullscreen from the controls, the native video player does hide the indicator for you.
> 
> We should probably still fix this though.

issue is when youre watching a video with embeded subtitles the subtitles disappear of you maximize.

**Comment by dannymichel** [comment]
https://github.com/th3rdwave/react-native-safe-area-context
