### ISSUE TITLE
Add support for http authentication

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#15]
We need to add support for http authentication. Currently it displays an error message that the server is unavailable.

**Comment by thornbill** [comment]
I experimented a bit with adding the username/password to the url and specifying an Authorization header in the webview source, but it seems like this will be blocked until upstream support is added.

Refs: https://github.com/react-native-webview/react-native-webview/issues/18

**Comment by jebeaudet** [comment]
Any updates on this?

**Comment by thornbill** [comment]
Nope. This issue would be updated if there was a status change.

**Comment by thornbill** [comment]
This is no longer planned. None of the Jellyfin apps support this and you are better off using a more secure solution like a VPN to prevent unauthorized access.
