### ISSUE TITLE
iOS - Music keeps playing without sound when phone is locked

### ISSUE THREAD

**Issue by matjaz321** [jellyfin/jellyfin-ios#153]
Hey,
So when I start playing a music and lock the screen, then the music continues playing for a few seconds and the sound disappears, but the track is still playing (so without sound).

**Comment by anthonylavado** [comment]
This is probably still #19. The player on the lockscreen likes to think it's still going, but the process is definitely gone.

**Comment by thornbill** [comment]
Yeah this is the same root issue as #19. I will close this one as a duplicate.
