### ISSUE TITLE
Disable screen lock by default

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#157]
Since background audio playback now works on iOS 14, we should disable the screen lock by default when on iOS 14+.

**Comment by darrindeal** [comment]
I would like to try and work on this. You just want the screen lock to not operate if device is iOS 14?

**Comment by thornbill** [comment]
The idea is that we could add a check [here](https://github.com/jellyfin/jellyfin-expo/blob/master/stores/SettingStore.js#L26) to change the default for that setting to be `false` if on iOS 14 or greater. It should be similar to the check for iPads for the rotation setting in that same file.

**Comment by ddedic** [comment]
Maybe my pull request #159 is sufficient?
