### ISSUE TITLE
Add new locales

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#161]
Any locales that have been added since the last release need to be added to the localization configuration.

[translations directory](https://github.com/jellyfin/jellyfin-expo/tree/master/langs)

[configuration file](https://github.com/jellyfin/jellyfin-expo/blob/master/i18n.js)

**Comment by JoaoVictorNascimento** [comment]
@thornbill  I will solve this issue

**Comment by anthonylavado** [comment]
Fixed by #162.
