### ISSUE TITLE
Implement optional native player

### ISSUE THREAD

**Issue by GiviMAD** [jellyfin/jellyfin-ios#169]
I was taking a look to the project and I think that implement an optional native player would be great.
I have no previous experience with expo but I saw this module in the sdk that seems to provide access to the native player. The idea will be to create a communication channel between the app and the webview to open the videos in the native web player on top of the webview. 
Do you think it's a good idea? I'm aware it will take quite work.
Thanks in advance for yours thoughts.

**Comment by nyanmisaka** [comment]
Would be great if a native player can be implemented!

For now, the player in webview supports a few containers and video profiles that will lead to unnecessary transcoding.
I have added fMP4 support from server side to make HEVC remuxing available on iOS as a beginning.

**Comment by thornbill** [comment]
Added in https://github.com/jellyfin/jellyfin-expo/pull/210
