### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by s3rverro0m** [jellyfin/jellyfin-ios#17]
When I put in my server URI (http, https and neither), the app says “Could not connect to server”.

JellyFin is behind Traefik which I have set the “Secure connection mode” to “Handled by Reverse Proxy”.

Please let me know if you need anymore information!

**Comment by anthonylavado** [comment]
Thanks for reporting this!

**Comment by Avi0n** [comment]
I am also running Jellyfin behind traefik and have no issues connecting through the iOS app. For reference, these are the traefik labels I am using in docker-compose:
```- "traefik.enable=true"
- "traefik.backend=jellyfin"
- "traefik.frontend.rule=Host:jellyfin.${DOMAINNAME}"
- "traefik.port=8096"
- "traefik.frontend.headers.SSLRedirect=true"
- "traefik.frontend.headers.STSSeconds=315360000"
- "traefik.frontend.headers.forceSTSHeader=true"

**Comment by s3rverro0m** [comment]
I’ll check out the labels I use! I was just thinking about this and this may be the issue. Thanks!

**Comment by s3rverro0m** [comment]
Looks like there’s an issue somewhere with my setup then. I enabled only the headers you have and I still can’t connect. 🙁

**Comment by Avi0n** [comment]
What version of Jellyfin and traefik are you using? Could you post your traefik.toml? Some other thoughts are to look at the logs for Jellyfin and Traefik when trying to connect with the iOS app.

**Comment by theg00s3** [comment]
try adding /jellyfin to your server URI (if you haven't already)

**Comment by gursimranp** [comment]
I’m getting the same issue, however, I’m running it behind nginx reverse proxy.

**Comment by s3rverro0m** [comment]
> try adding /jellyfin to your server URI (if you haven't already)

This actually worked for me!

**Comment by dkanada** [comment]
The original issue has been resolved so I will close this. @gursimranp if you still can't connect please feel free to open a new issue.
