### ISSUE TITLE
Continue listening for audio content

### ISSUE THREAD

**Issue by jdmarshall90** [jellyfin/jellyfin-ios#172]
For videos, my watch progress saves and shows up on the launch UI. Audio content, specifically my podcasts, do not do this so I always have to manually find where I left off, otherwise it just tries to restart from the beginning.

Same problem occurs when trying to switch devices using the "play on" feature.

**Comment by ReubenBTalbott** [comment]
+1 on this! I would love to be able to easily play my audiobooks from jellyfin, I have a lot of Brandon Sanderson books that are 40+ hours so finding where I left off is not an option 😂

**Comment by anthonylavado** [comment]
I believe this is a limitation of the server, not the client. I'll check in the morning.

**Comment by ReubenBTalbott** [comment]
Looks like this may be fixed in Jellyfin 10.7.0 https://github.com/jellyfin/jellyfin/issues/4897

**Comment by thornbill** [comment]
Should be fixed in server version 10.7.
