### ISSUE TITLE
Impossible to use the Home icon

### ISSUE THREAD

**Issue by LoMGolden** [jellyfin/jellyfin-ios#195]
Hello,

I think a identified a bug because I can’t use the Home icon when I’m navigating in my movie section.
But Thanks for all the time you spent free in this project :)

**Comment by thornbill** [comment]
What server version is this happening for? Also is this the icon in the header or the tab bar at the bottom? Thanks!

**Comment by LoMGolden** [comment]
> What server version is this happening for? Also is this the icon in the header or the tab bar at the bottom? Thanks!

I use the last stable server version on Debian, and it’s the home icon in the tab bar ! (I guess it is). I see there’re some bugs with the others icon of the same tab bar, but also that those bugs are happening on the browser of my smartphone too (I use an iPhone 8 running on the last iOS version).
But no problem when I’m on my computer using Firefox.
Hope I helped !

**Comment by thornbill** [comment]
Just to be clear, here is what I mean by the header and the tab bar. Thanks!

![9EAF195E-1057-4A74-9AB5-2470DE51B490](https://user-images.githubusercontent.com/3450688/103363894-49db8e80-4a8a-11eb-86de-0bdff4fe8051.jpeg)

**Comment by LoMGolden** [comment]
Ooops sorry I talked about the header... It’s seems that the issue disappears now. I think I experienced a poor connection (my server is distant) and it the header buttons have lagged because of this. But it’s really strange...

**Comment by thornbill** [comment]
Closing since the last comment says the issue resolved itself.
