### ISSUE TITLE
Videos Do Not Resume

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-ios#20]
Hearing this from a user on Reddit:
When the app is backgrounded and killed by iOS, audio will resume when you return to it, but not video.

We should explore saving the state and recovering better.

**Comment by drazil100** [comment]
After finding the repo I went and did some more in depth testing. Seems both resume. I think it just bugged out before but it works now? (server is running on a machine that was built in 2009 so its a bit slow) 

To get both to resume you have to pause it and unpause it. It doesnt recognize it was paused by iOS.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
I have the same issue. However, my "play" button simply disappears so I have no way of resuming without refreshing everything and manually finding where I left off.

**Comment by thornbill** [comment]
@k6Q28k5w5eWuRuuzTg9j7GrKCbjt7 the play button disappearing is a known issue in jellyfin-web. See https://github.com/jellyfin/jellyfin-web/issues/530. Hopefully it will be fixed in the next release!

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
Oh, sry about that. 

Another observation (Unsure if this is related to resume issue or not, or if it is known). Every time I resume a video (when I can), subtitles get out of sync. If I restart the video, its corrected (manually resume). I can reproduce this consistently across various embedded sub formats (mkv container). Only occurs on the iOS app (I havent observed the same on other devices yet when checking the same video file, so far at least).

**Comment by thornbill** [comment]
Is anyone still having issues resuming in the app? (There is a separate issue for subtitles being out of sync.)
