### ISSUE TITLE
App rotates to portait veiw after launch

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-ios#21]
After launching the app in landscape view on an iPad Pro 11 (iOS13.3) the App rotates into portrait view. You have to rotate the iPad up and down again to get back to landscape mode.

**Comment by RealDyllon** [comment]
I can't reproduce this issue. Could you link a screen recording?

**Comment by RealDyllon** [comment]
I loaded the testflight version and encountered the issue.

**Comment by RealDyllon** [comment]
I've submitted a pull request: https://github.com/jellyfin/jellyfin-expo/pull/25 with a potential fix. It seems to work for me on my iPad mini.

**Comment by RealDyllon** [comment]
I updated the TestFlight app to the latest build but the issue persists. Let me see what I can do over the weekend. It may have to do with the difference between **ScreenOrientation.UnlockAsync** vs **ScreenOrietation.LockAsync**

**Comment by thornbill** [comment]
@RealDyllon your change has not been published to TestFlight yet.

**Comment by Nickbert7** [comment]
It seems to be fixed in the latest testflight version.

**Comment by RealDyllon** [comment]
Great news, looks like app.json was the solution.
