### ISSUE TITLE
Can't shuffle or play all on photo library with subfolders

### ISSUE THREAD

**Issue by VerbTheNoun95** [jellyfin/jellyfin-ios#212]
Details:
> Jellyfin Mobile version 1.3.0 (5.3.1.1)
> Expo version 39.0.0
> Both Jellyfin server version 10.6.4 arm and 10.7 docker

Tapping on play all or shuffle brings up an error box saying that the server is sending an incompatible media format. I did some digging and wrote up the cause in the browser client [here](https://www.reddit.com/r/jellyfin/comments/le5ohc/any_way_to_get_more_verbose_logs_when_playing/), but to reiterate the presence of a folder in the library root causes the client to send a GET request to the server with a query that specifies audio and video as the media type and does not include photos.

This is an easy fix for me on the web client, but I don't know where to begin with react/expo. I don't see anything pertaining to the `playbackmanager` in the expo app, but it should be as simple as adding photo to the media types to look for when getting the list of items to play. I'm pretty sure photos were left out to avoid serving things like cover art along with an album or movie within a folder, so I'm reluctant to formally request this as a feature to be added. At least not using this particular solution.

If someone could point me towards where the expo client asks for a list of items to play when tapping playall/shuffle, I would appreciate it. I'd be happy to look into it on my own time. Thanks!

**Comment by thornbill** [comment]
For the most part this app is just a wrapper for the web interface. I would expect it to work with the web change you made without any changes needed in the app.

**Comment by VerbTheNoun95** [comment]
Gotcha, that makes things clearer! I'll dig around and see if I can figure out how the app wraps around the client. This isn't so much an issue since I'll likely make these changes on my own, so I'll close this out. Thanks!
