### ISSUE TITLE
Error when adding ‚&‘ to username

### ISSUE THREAD

**Issue by jonastaedcke** [jellyfin/jellyfin-ios#213]
I can’t add ‘&’ to the usernames name

**Comment by camc314** [comment]
Can you input it in the web client?

**Comment by jonastaedcke** [comment]
Yes I can type this in the web client. When I try to add a new profile with the name "Test & Test" I receive this error message: There was an error processing the request. Please try again later.

When I add a new profile (without the & in name) and rename their name to "Test & Test" everything works as excepted.

**Comment by camc314** [comment]
It looks like this may be intended behaviour

I've created an issue in jellyfin/jellyfin since this isn't an issue exclusive to jellyfin-expo

This can now be closed.
