### ISSUE TITLE
Download feature doesn't appear to work

### ISSUE THREAD

**Issue by kkasberg** [jellyfin/jellyfin-ios#22]
I attempted to download a movie for local playback, but I cannot determine how to know when it is downloaded, or where to play if from.

**Comment by simoncaron** [comment]
![8CCEB3D1-A298-4028-AFAB-1F8E374D07BC](https://user-images.githubusercontent.com/8635747/69487803-0b5ab580-0e2e-11ea-80ab-f604c0646816.jpeg)

**Comment by thornbill** [comment]
The download option should be removed in the latest update until we can get it working properly.

**Comment by Bitwolfies** [comment]
While im no dev, an app I used for my plex music called "prism" used apples new files app to store downloaded music, maybe that's a way you could implement downloads.

**Comment by thornbill** [comment]
It looks like we could enable [some options](https://stackoverflow.com/a/51383196/1373956) to allow other apps to access the downloaded files. Additionally we may be able to use [showShareActionSheetWithOptions](https://docs.expo.io/versions/latest/react-native/actionsheetios/#showshareactionsheetwithoptions) to open an action sheet to open the downloads in another app. I will see if I can get it working after 1.2.0 is out.

**Comment by Bitwolfies** [comment]
> 
> 
> It looks like we could enable [some options](https://stackoverflow.com/a/51383196/1373956) to allow other apps to access the downloaded files. Additionally we may be able to use [showShareActionSheetWithOptions](https://docs.expo.io/versions/latest/react-native/actionsheetios/#showshareactionsheetwithoptions) to open an action sheet to open the downloads in another app. I will see if I can get it working after 1.2.0 is out.

Great, I hope it works out!

**Comment by leocaseiro** [comment]
This is a reference https://github.com/florentroques/expo-download-and-play-video-example which I found here https://forums.expo.io/t/best-practice-for-downloading-videos-storing-file-locally-and-playing-in-app/447/2

**Comment by thornbill** [comment]
An option to enable an experimental download feature has been added under the developer menu but that has not been released yet. Further improvements to that feature are tracked in https://github.com/jellyfin/jellyfin-expo/issues/372.

**Comment by leocaseiro** [comment]
Thank you so much @thornbill 

🚀

**Comment by fugohan** [comment]
When will v1.6.0 be released? @thornbill

**Comment by thornbill** [comment]
https://github.com/jellyfin/jellyfin-meta/discussions/62
