### ISSUE TITLE
No way to shuffle all music on iOS

### ISSUE THREAD

**Issue by jqdg** [jellyfin/jellyfin-ios#230]
Shuffling the entire music library can be achieved either by right-clicking the library or hovering and accessing the "three dots" contextual menu on the home screen.

On iOS (as far as I know) there is no way to right-click or hover in order to access this menu. I don't know of another way to shuffle the entire library.

It would be great if there was some way to achieve this on iOS (I would suggest that long tap would perform the same action as right-clicking, but long tap does something else currently).

**Comment by thornbill** [comment]
While not ideal you should be able to shuffle all from the albums tab of a music library currently.

![56591D56-5641-4BE2-AFE8-2237937C2E85](https://user-images.githubusercontent.com/3450688/110370536-c99d5080-8019-11eb-842b-09d1d5d36d02.jpeg)

**Comment by jqdg** [comment]
I didn't know about that, thanks for pointing it out!

**Comment by thornbill** [comment]
Closing this since there is a feature request to add the shuffle option to additional screens here: https://features.jellyfin.org/posts/625/music-shuffle-all
