### ISSUE TITLE
Flac file won't play on Iphone  - fails with ffmpeg error

### ISSUE THREAD

**Issue by sod75** [jellyfin/jellyfin-ios#24]
**Describe the bug**
Playing a flac file on iphone in either the app or in firefox shows the file playing but no sound. 
Playing the same file on the server via firefox works ok

**To Reproduce**
Play a FLAC music file on iphone via testflight app or in browser

**Expected behavior**
file plays ( with sound)

**Logs**
```
http://192.168.0.10:8096/Audio/10b66951da219c3a06ccf6a74a321089/hls1/main/20.aac?UserId=44f60de0f07d4206ba44db2e77fe47aa&DeviceId=TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxMl8zXzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBNb2JpbGUvMTVFMTQ4fDE1NzUwMzczMzE0MDM1&MaxStreamingBitrate=800000&Container=mp3%7Cmp3%2Caac%2Cm4a%7Caac%2Cflac%2Cwav&TranscodingContainer=aac&TranscodingProtocol=hls&AudioCodec=aac&api_key=1bf0afbeb5d341418020119642f8c66c&PlaySessionId=1575051617482&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false&SegmentContainer=aac

{"Protocol":"File","Id":"10b66951da219c3a06ccf6a74a321089","Path":"/data/muziek/Amon Amarth/2008 Twilight Of The Thunder God/01 Twilight Of The Thunder God.flac","Type":"Default","Container":"flac","Size":32282954,"Name":"01 Twilight Of The Thunder God","IsRemote":false,"ETag":"7231f653b9d99aeed300dc208954a357","RunTimeTicks":2487470080,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"flac","TimeBase":"1/44100","CodecTimeBase":"1/44100","DisplayTitle":"FLAC stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitDepth":16,"Channels":2,"SampleRate":44100,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":1038259,"RequiredHttpHeaders":{}}

/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:01:00.000 -i file:"/data/muziek/Amon Amarth/2008 Twilight Of The Thunder God/01 Twilight Of The Thunder God.flac" -map_metadata -1 -map_chapters -1 -threads 0   -acodec aac -strict experimental -ac 2 -vn -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type aac -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/7326e8e4af757c334d22674e53c1af1e%d.aac" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/7326e8e4af757c334d22674e53c1af1e.m3u8"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Ubuntu 8.3.0-6ubuntu1)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, flac, from 'file:/data/muziek/Amon Amarth/2008 Twilight Of The Thunder God/01 Twilight Of The Thunder God.flac':
  Metadata:
    ALBUM           : Twilight of the Thunder God
    album_artist    : Amon Amarth
    ARTIST          : Amon Amarth
    date            : 2008
    genre           : Metal
    TITLE           : Twilight of the Thunder God
    track           : 01
  Duration: 00:04:08.75, start: 0.000000, bitrate: 1038 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
[hls muxer @ 0x56486bdd8f40] [Eval @ 0x7ffe8f62d890] Undefined constant or missing '(' in 'aac'
[hls muxer @ 0x56486bdd8f40] Unable to parse option value "aac"
[hls muxer @ 0x56486bdd8f40] Error setting option hls_segment_type to value aac.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
[aac @ 0x56486bddb140] Qavg: -nan
Conversion failed!
```

**System :**
 - OS: [Kubuntu 19.04 x86_64]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [10.4.2-1]
 - Reverse proxy: [none, on LAN]

**Additional context**
works fine on Jellyfin version: "10.3.7.0"

**Comment by TheNamelessWonderer** [comment]
This applies to iPhones using Safari or the App and isn’t related to the app at all. Shouldn’t this have stayed in the main repository?

**Comment by TheNamelessWonderer** [comment]
Also I have just tested this running 10.4.3 on macOS and FLAC files play perfectly but ALAC don’t have any sound and are being transcoded to AAC. On my iPad Air 2 running 13.3 FLAC files are being directly played but ALAC are bring transcoded.

**Comment by thornbill** [comment]
@dkanada perhaps this should have stayed in the server repo?

**Comment by sod75** [comment]
I upgraded the server to Jellyfin version: "10.4.3" and it plays the files ok on the iphone now both in app and browser

**Comment by TheNamelessWonderer** [comment]
What file did you try? Only FLAC?

13 Dec 2019, 08:19 by notifications@github.com:

**Comment by sod75** [comment]
> What file did you try? Only FLAC?

others (mp3, videos) play fine too but also did on 10.4.2,  the only ones that wouldn't play on the previous version as far as I could tell were flac. I no longer see logs of (failed) attempt to transcode them either anymore now on 10.4.3, so it looks solved to me.

(just in case it's relevant, the ios was also upgraded from v12 to v13 in the mean time)

**Comment by sod75** [comment]
hmmm....further info but weird.
i updated the ios client to 0.1.0. it still works on lan  (phone on local wifi with the server specified as http://192.168.0.x:8096) but when I turn of wifi and choose the server as http://myddns.net:8096 ( woth portforwarding) the flac tries to transcode and fails. MP3 files play fine.

see failed log
[flac_failed_10.4.3with_ios0.1.0.txt](https://github.com/jellyfin/jellyfin-expo/files/3968139/flac_failed_10.4.3with_ios0.1.0.txt)

**Comment by anthonylavado** [comment]
Interesting... thanks for the logs and context info!

We were wondering how it was broken because it seemed to always work for us... didn’t think to try over a remote connection.

There’s a couple things to try/check:

- If you go to the Dashboard, and choose “Playback”, then go to the “Streaming” tab, is there anything written in for “Internet streaming bitrate limit”?

- If you go to Users, and open your own user account, scroll down, is there anything listed for bitrate limit there?

- In the user settings, if you uncheck “Allow audio playback that requires transcoding”, and try it again, does it work?

**Comment by sod75** [comment]
> If you go to the Dashboard, and choose “Playback”, then go to the “Streaming” tab, is there anything written in for “Internet streaming bitrate limit”?

No, it's empty

> If you go to Users, and open your own user account, scroll down, is there anything listed for bitrate limit there?

no, empty as well

> In the user settings, if you uncheck “Allow audio playback that requires transcoding”, and try it again, does it work?

Yes! It does.

**Comment by anthonylavado** [comment]
@sod75 We’ve figured it out since. There’s a command with FFmpeg that we modified to fix other streaming, and that seems to have impacted this.

It’s possible to fix, but there’s also some concerns. Do we stream full FLAC outside of the network? What if you want to save on data and are willing to have it transcoded to AAC? Should this be a setting?

I’m personally in favour of having a setting (“Full quality, Good quality, data saver”), but this would require our database changes (which are in the works).

**Comment by gnattu** [comment]
The PR jellyfin/jellyfin#2216 should also fix this problem. I tested the flac playback on iPhone and it works.

**Comment by thornbill** [comment]
I'm going to close this since it should be fixed in the next server release. Thanks!
