### ISSUE TITLE
Music player status bar covers "More Like This" artists and titles

### ISSUE THREAD

**Issue by tonywagner** [jellyfin/jellyfin-ios#259]
Love the app! But when I am playing music, the player status bar covers up the "More Like This" artist name or album title. Here's what it looks like on my iPhone 6s:

![94410](https://user-images.githubusercontent.com/2084637/115255603-0a49b880-a0f4-11eb-8a95-0700b24580ad.jpg)

I can sometimes scroll the page up momentarily to see the text underneath, but of course it bounces back down right away. And even that ability goes away when I begin scrolling horizontally through the "More Like This" list.

I'm on the latest versions of both iOS and the Jellyfin iOS app.

**Comment by thornbill** [comment]
This is an issue with the web interface that is being tracked here: https://github.com/jellyfin/jellyfin-web/issues/1035
