### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by nostromo128** [jellyfin/jellyfin-ios#263]
I’m not a Tekkie at all. My jellyfin has not worked for days on my iPad and iPhone. Help? Please dm me jellyfin.

**Comment by joshuaboniface** [comment]
This is not a support forum. Please see [our subreddit](https://reddit.com/r/jellyfin) for assistance with Jellyfin. You will also need to provide more information about the specific problem(s) you're encountering, logs, etc.
