### ISSUE TITLE
Carga de videos 

### ISSUE THREAD

**Issue by Arauz393** [jellyfin/jellyfin-ios#288]
La reproducción de videos se encuentra presentado problemas. A pesar de que la calidad del video es SDR no va fluido.

**Comment by ferferga** [comment]
Hola

¿Puedes aportar más detalles, por favor? Logs del servidor, codecs del video, dispositivo...

Todos los detalles que puedas aportar son buenos para entender qué está pasando. Pero la descripción que has dado no es suficiente.

Un saludo.
