### ISSUE TITLE
Issue with Tv Guide Epg

### ISSUE THREAD

**Issue by TheDeatCrusher** [jellyfin/jellyfin-ios#295]
Hello I entered my epg and when I refreshed the guide there’s nothing on the guide it’s blank someone pls help

**Comment by thornbill** [comment]
This is probably a server side issue and not one specific to the iOS app. Please create an issue for it [here](https://github.com/jellyfin/jellyfin/issues) and include all the requested information if a similar issue does not already exist. Thanks!
