### ISSUE TITLE
Actual Chromecast device is not shown in device dropdown

### ISSUE THREAD

**Issue by edenman** [jellyfin/jellyfin-ios#309]
![IMG_9372 2](https://user-images.githubusercontent.com/1063557/136678479-7d7392be-490c-4213-9443-216b2e779d91.jpg)

It only shows my web browser on my computer and the DLNA device for my audio receiver.   Not showing the actual Chromecast device.  I tried changing the Chromecast setting on the server to "Unstable" but that didn't help.

Jellyfin server 10.7.7
iOS app 1.4.1 (5.4.1.0)
Expo Version: 39.0.0

**Comment by anthonylavado** [comment]
Yeah, the other issue is still the best place for this :-)
