### ISSUE TITLE
Inquiry - iOS Native Player

### ISSUE THREAD

**Issue by LePips** [jellyfin/jellyfin-ios#314]
Hello there, I'm looking at grabbing the `master.m3u8` stream for Swiftfin for native player implementation and am wondering how the expo app currently implements it along with subtitles. I can get and construct the `master.m3u8` stream just fine except for subtitles.

If there is an insight or direction to how the native player is implemented that would be great! Even if the current route that I'm going on isn't the correct one.

**Comment by thornbill** [comment]
This app just gets passed the url from web. 😅 I believe that is pretty much all handled in [this file](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/playback/playbackmanager.js), but it is a bit messy in there lol.

**Comment by LePips** [comment]
If anything, that probably makes thing a lot easier. Thanks!
