### ISSUE TITLE
Not hiding orientation indicator on iOS when playing movie or when in menu in landscape orientation

### ISSUE THREAD

**Issue by foss-** [jellyfin/jellyfin-ios#335]
**Describe the bug**
The white bar used as orientation indicator on iOS never vanishes when watching a movie. While the player controls disappear after a brief moment, the white bar stays always on screen. This is also true when in menu in landscape orientation.

**System (please complete the following information):**
 - iOS Version: 15.2.1
 - Jellyfin Expo version: 1.4.1
 - Jellyfin Server version: 10.7.7

**Comment by anthonylavado** [comment]
Duplicate of #188.
