### ISSUE TITLE
When will it be released

### ISSUE THREAD

**Issue by CoderMaurice** [jellyfin/jellyfin-ios#34]
I compiled and tested the app, but unfortunately it can only be tested on the LAN, when will it be released?

**Comment by thornbill** [comment]
If you have configured your server and network to make Jellyfin available outside of your lan then you should be able to connect to it remotely from the app.

The app is available for iOS via TestFlight currently. (https://testflight.apple.com/join/TcFUEVEb)

**Comment by CoderMaurice** [comment]
I have installed and it works well, thanks!

**Comment by CoderMaurice** [comment]
By the way, will this project connect to Weblate?
I would be glad to contribute.

**Comment by thornbill** [comment]
Glad it is working for you! We do plan to add localization support and use weblate to handle translations. That will be tracked in this ticket https://github.com/jellyfin/jellyfin-expo/issues/4.
