### ISSUE TITLE
Black screen with HEVC 265 mp4 videos

### ISSUE THREAD

**Issue by tacocats** [jellyfin/jellyfin-ios#344]
When trying to play any video that is an MP4 with HEVC 265 coding I will get a black screen, but the sound will still play. Videos with HEVC 264 encoding will play fine however. Is this something that would be related to the app itself not supporting HEVC 265 encoding or is this likely something related to iOS?

Some things I noticed, is on the fly transcoding will allow playback, but it's too much load on my simple server to be usable. Due to this I disabled transcoding on my Jellyfin server. Also while experimenting with getting the HEVC 265 MP4 files to play on my phone from the server, I found using VLC was able to play them. Since VLC is able to play them, I was assuming it might be an issue with this app itself, any ideas?

I'm on an iPhone 11 running Version 15.3.1

**Comment by anthonylavado** [comment]
Just to be clear, is this with Jellyfin/Jellyfin Mobile (purple regular icon), or Swiftfin (blue icon)?

**Comment by tacocats** [comment]
> Just to be clear, is this with Jellyfin/Jellyfin Mobile (purple regular icon), or Swiftfin (blue icon)?

Yup, Jellyfin Mobile the settings menu has this info at the bottom:
```
Jellyfin Mobile (iOS)
1.4.1 (5.4.1.0)
Expo Version: 39.0.0
```

I didn't know about Swiftfin, I may give that a try and see if it can load the videos later or if it has same issue.

**Comment by anthonylavado** [comment]
The H265 may work with the Native Video Player option in the settings. It's worth a shot.

**Comment by thornbill** [comment]
If something does not play when transcoding is disabled, but transcodes and plays when transcoding is enabled, then the media cannot be played directly by the device. This is expected and is the whole point of having a system like Jellyfin that can handle transcoding.

VLC playing something is irrelevant since it uses its own libraries for media playback not the system media libraries.
