### ISSUE TITLE
could not connect to not secure http server or maybe with custom port

### ISSUE THREAD

**Issue by yalagin** [jellyfin/jellyfin-ios#369]
**Describe the bug**
could not connect to not secure http server : http://example.thddns.net:8880/
only  https://example.thddns.net:8880/ urls are allowed 
or maybe it's because I have custom port 8880 
Swiftfin also don't work 

**I get an error**
could not connect to server

**System (please complete the following information):**
 - iOS Version: 15
 - Jellyfin Expo version: 1.4.1(5.4.1.0)
 - Jellyfin Server version:10.7.7

**To Reproduce**
I am trying to add my own server (http://example.thddns.net:8880/) with  http://  not secure connection 
with custom port 8880 and it's not working. I tried Finamp and it is working

**Comment by thornbill** [comment]
It sounds like you may have a configuration issue here. https and http cannot operate on the same port, so if https is working on 8880 you would need to configure a different port for http. Please verify you can connect in a browser before opening issues for specific apps. If you need more help with your setup, check out the resources available at https://jellyfin.org/docs/general/getting-help.html.
