### ISSUE TITLE
Can't get into Playlists from Library icon

### ISSUE THREAD

**Issue by drazil100** [jellyfin/jellyfin-ios#37]
Tapping on the library icon for Playlists does absolutely nothing. The only way to access your playlists is through the tab in a music library.

**Comment by thornbill** [comment]
Could you provide a screenshot? I’m not sure where the library icon is that you are referring to. Thanks!

**Comment by drazil100** [comment]
![EA43328F-7F00-426C-B6EA-810AA2303448](https://user-images.githubusercontent.com/17794391/72036437-70dcf700-3260-11ea-90e2-ed3f1ced5dd8.jpeg)

Clicking this has no response. Can access from the tab in music libraries but not from the home page.

**Comment by drazil100** [comment]
Suddenly it works again. It didn’t work after closing the app completely and reopening several times but now it just always works.
