### ISSUE TITLE
Comic book pages get cut off horizontally

### ISSUE THREAD

**Issue by rourien** [jellyfin/jellyfin-ios#382]
### Describe the bug

The pages of comic books get cut off on the right side of my iPhone 8. It is most noticeable for double-sided pages where two pages are one image. It looks as if the reader scales to the height of the image, but ignores the width. I haven't tried the reader on a different device with a higher resolution than the iPhone 8's 1334x750 resolution. The resolution of the comic book page shown in the video below is 1988x1588. You can see that the only way to see the rest of the image that is cut off is to zoom in, and even then, it doesn't get the whole thing. 
Would it work to compare the device's width and the image's width to the device's height and the image's height? In the example above, the difference between the iPhone's width and the image's width is larger than the iPhone's height and the image's height, so scale the image to the iPhone's width.

comic book format: cbz
comic book image format: jpg

https://i.imgur.com/bpp4fCw.mp4

PS: a new feature that would be nice is a full screen mode where image covers the whole screen and not have the status bar at the top and the home and settings buttons at the bottom

### Application version

1.5.0 (5.5.0.0)

### Where did you install the app from?

App Store

### Device information

iPhone 8

### OS version

iOS 14.7.1

### Jellyfin server version

10.8.1

**Comment by thornbill** [comment]
Should be fixed in the next major Jellyfin release (10.9.0).
