### ISSUE TITLE
Cannot add a home local server

### ISSUE THREAD

**Issue by shaohao** [jellyfin/jellyfin-ios#389]
iOS app.I cannot add a home local server with url : https://movie.myhome/

**Comment by shaohao** [comment]
I cannot add a home local server with url :  https://movie.myhome

**Comment by thornbill** [comment]
Are you using a self-signed certificate for https?

**Comment by shaohao** [comment]
Yes, I am using a self-signed certificate for https.

BTW: If I try to input my url:
https://movie.myhome
The app tells me the url is invalid
But, If I try to input url:
https://movie.myhome.com
The app can recognize this url.

**Comment by thornbill** [comment]
We don't provide any support for self-signed certificates. You might be able to get it to work by installing the generated root CA in iOS but we don't encourage or support that directly.

I'm not sure what your setup is as far as your domains go, but the two examples you give are two entirely different domains (only one of which includes a valid TLD) I would not expect those to behave the same.
