### ISSUE TITLE
White screen when returning to app

### ISSUE THREAD

**Issue by tknx** [jellyfin/jellyfin-ios#396]
**Describe the bug**

If I go away from the app and then go to the app switcher, the app will show a white screen. Sometimes refreshing by pulling down fixes it but most of the time not. 

**System (please complete the following information):**

 - iOS Version: 16.1 public beta (but has been happening for a while)
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: current

**To Reproduce**

1. Start Jellyfin 
2. Switch to another app and leave Jellyfin in the background d for some time
3. Swipe up to get app switcher and can see white screen attached to Jellyfin app 

**Expected behavior**
App resumes

**Screenshots**

I'll add some when next time it happens. 

**Additional context**

None

**Comment by tknx** [comment]
Here are some screenshots

![image](https://user-images.githubusercontent.com/29260341/193430698-a53aaa73-fd73-4825-9bcb-457dd84bcd33.png)

![image](https://user-images.githubusercontent.com/29260341/193430700-bb9561c8-0396-465c-89d4-5350a5cdd0ba.png)

**Comment by thornbill** [comment]
I've never seen this one. Were you playing a video before leaving the app? Or is there a chance the server was temporarily unavailable due to a network status change or something?

**Comment by anthonylavado** [comment]
I occasionally get this. I just pull down to refresh and it's good. I haven't monitored what it is that could be causing it. I don't believe playback is involved at all. It's almost like a session timing out.

**Comment by tknx** [comment]
@thornbill it happens pretty consistently for me and I suspect it is a timeout or memory clearing of the iOS device.

But that being said, a pull down refresh only works sometimes for me, I often have to forcequit the app and reload.

**Comment by thornbill** [comment]
Looks like this is caused by https://github.com/react-native-webview/react-native-webview/issues/2298. We will need to refresh the webview when the app resumes.
