### ISSUE TITLE
Unable to move the progress cursor when streaming to my xbox one

### ISSUE THREAD

**Issue by remz1337** [jellyfin/jellyfin-ios#402]
**Describe the bug**
When casting from my mobile device to my xbox one (it uses the default media player app of the xbox), the content (movie, tv show) always starts from the beginning and can't be resumed from half-way through. I can forward a bit using the +30 seconds and waiting for it to load every time, but not practical if I want to get back to 1 hour in the movie. When I try to drag the cursor on the progress bar, both in the mobile app or in the xbox app, it keeps restarting the content from the beginning.

**System (please complete the following information):**
Been happening for since I put Jellyfin in place about a year ago.
 - iOS Version: happened on 15 and 16
 - Jellyfin Expo version: I don't know, I keep my apps up to date
 - Jellyfin Server version: 10.8.3

**To Reproduce**

Open Xbox one
Open mobile app
Start a movie
Cast it to the xbox
Try to drag the progression cursor half-way through the movie

**Expected behavior**
The movie resume at the selected time

**Comment by thornbill** [comment]
Have you tried this in Safari? Just curious if this should be moved to jellyfin-web.

**Comment by remz1337** [comment]
Hmm so opened up everything today to do some tests and the app doesn't list my xbox as 1 of the cast target...
I found the videotape xbox app that seems to work great so far. I also tried simply using the web interface using the Edge browser on Xbox and works good too. I can also control from my phone that way.

So anyway, closing this. Keep up the good work!
