### ISSUE TITLE
I need VR client 

### ISSUE THREAD

**Issue by zs20221102** [jellyfin/jellyfin-ios#404]
When I’m watching videos，using Jellyfin APP is much faster than using WEB especially when I’m playing big VR video files. 

It seams there’s no Jellyfin app for VR equipment. So I have to use WEB to watch VR videos on my VR gears， it gets stuck and stopped，really bad.

So why don’t we develop apps on Oculus quest(Meta)，HTC VIVE，HTC VIVE FLOW？

**Comment by anthonylavado** [comment]
The really isn't the best place to have out this request.

Feature requests for the whole project go here: https://features.jellyfin.org

While I don't use any of those pieces of VR Equipment, I believe some have experimented with using the Android apps on them. YMMV.
