### ISSUE TITLE
Offline music

### ISSUE THREAD

**Issue by alfwro13** [jellyfin/jellyfin-ios#409]
**Describe the feature**
It would be fantastic if it was possible to mark tracks/playlists/albums for offline access

**Additional context**

**Comment by anthonylavado** [comment]
While we are working on enhancements for the main app, may I suggest some alternate clients?

Finamp is a popular option, and it's in the App Store: https://github.com/UnicornsOnLSD/finamp

**Comment by alfwro13** [comment]
Thanks for the suggestion - that app does exactly what I need.
