### ISSUE TITLE
Search results don’t appear when using “Identify” function.

### ISSUE THREAD

**Issue by DiamondPG** [jellyfin/jellyfin-ios#429]
When I try to identify something using the menu, nothing shows up in search results. Possibility for a local issue, but the internet is tied into the network. I don’t see why it can’t load anything.

**Comment by thornbill** [comment]
This would likely be a server side issue. Please check the logs when the search fails and create an issue with the requested information [here](https://github.com/jellyfin/jellyfin/issues) if a similar issue does not already exist. Thanks!
