### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by mat926** [jellyfin/jellyfin-ios#438]
**Describe the bug**

I cannot connect to my server or even the demo server and getting the message "Could not connect to server" . I can still connect to it through Safari. 

**System (please complete the following information):**
 - iOS Version: iPad OS 16.6
 - Jellyfin Expo version: I don't know
 - Jellyfin Server version: 10.8.10

**To Reproduce**

1. Open Jellyfin 
2. Enter the server address (ex.  demo.jellyfin.org) 

**Expected behavior**

The app should connect to the server 

**Screenshots**

App
![image](https://github.com/jellyfin/jellyfin-expo/assets/46114199/93a6e921-005c-4e83-a724-a760e3432274)

Safari
![image](https://github.com/jellyfin/jellyfin-expo/assets/46114199/c75e73c4-2345-4e26-9745-70075e8a3d31)

Jellyfin entry missing in iOS settings 
![image](https://github.com/jellyfin/jellyfin-expo/assets/46114199/ce45ac23-fa3e-4740-9ee7-55f2f68abc91)

**Additional context**

I keep getting this error in the iOS whenever I try to enter my server. I can access it through Safari but not in the app. I even tried it with the demo server (demo.jellyfin.org) and I'm getting the same error.  The app has access to Nearby Devices permission,  although Jellyfin is not listed in the iOS settings app. I tried with http and https. I am not using a VPN.

**Comment by anthonylavado** [comment]
For the demo server, try the full address itself:
https://demo.jellyfin.org/stable

Does that work in the app?

**Comment by thornbill** [comment]
Closing as stale
