### ISSUE TITLE
Newer Expo SDK

### ISSUE THREAD

**Issue by thiswallz** [jellyfin/jellyfin-ios#462]
Seems this app is using sdk 46 which causes a lot of issues for trying and building for expo, since is already deprecated, is there something we can do to use a newer one?

thanks!

**Comment by thornbill** [comment]
Unfortunately Expo 46 was the last version to support classic builds so we need to figure out a path forward for publishing builds without subscribing to expo's build service... but we should still upgrade. It's really just a matter of having the time to do it. It's not unusual for a couple things to break but their upgrade notes normally document anything breaking pretty well.

**Comment by DrNgo** [comment]
@thornbill i'm in the process of upgrading expo to 50 and changing the deployment of the app to build using github actions and submit it to testflight for testing. Let me know if there's something specific You want me to do regarding these steps

**Comment by thornbill** [comment]
The help would definitely be appreciated @DrNgo. My preference would be for one PR per Expo version like [this](https://github.com/jellyfin/jellyfin-expo/pull/422) for example. I did attempt to make a GH Action for builds previously but it [did not work](https://github.com/jellyfin/jellyfin-expo/pull/407). Also it wasn't clear in your comment but please do not publish a TestFlight build under your own account. Anthony manages publishing all of our official apps and I'm not sure if that would impede our official version.

**Comment by ebg1223** [comment]
@thornbill @DrNgo i work in rn / expo daily. Happy to help with this if someone has a WIP. Have lots of example deployments I can pull from

**Comment by thornbill** [comment]
Closing this one in favor of https://github.com/jellyfin/jellyfin-expo/issues/492 with links to the release notes.
