### ISSUE TITLE
Ability to set custom color scheme to match custom css

### ISSUE THREAD

**Issue by WolframCrem** [jellyfin/jellyfin-ios#470]
**Describe the feature**
It would add a setting inside the settings tab where you could change the settings from [colors.js](https://github.com/jellyfin/jellyfin-expo/tree/master/constants)

so in case the user has a custom css in jellyfin the user can match the app to the same color scheme
**Additional context**

maybe add the default colors so the user knows what they are editing

**Comment by thornbill** [comment]
Related meta discussion: https://github.com/jellyfin/jellyfin-meta/discussions/81

**Comment by thornbill** [comment]
Closing in favor of the meta discussion.
