### ISSUE TITLE
Native video player crashes app on playback since iOS 17.2

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-ios#471]
**Describe the bug**
Upon pressing play, Jellyfin Mobile repeatedly crashes back to the springboard. Unchecking using. The native player has it play again. This is new since iOS 17.2 that came out recently.

**System (please complete the following information):**
 - iOS Version: 17.2
 - Jellyfin Expo version: 43.0.0 / 1.5.0
 - Jellyfin Server version: 10.8.13

**To Reproduce**

1. Turn on native playing
2. Find a movie
3. Press play.

**Expected behavior**
Playing video

**Comment by thornbill** [comment]
Can confirm. It's busted. 🫠

**Comment by outtahere** [comment]
Affected also. Agree with the above.

**Comment by MarcModica** [comment]
Same here, iOS 17.2, iPhone 13 Pro. Completely broken. Sad as it’s the only way of direct playing HVEC with multichannel audio. Now forced to use Swiftfin or play the file from VLC. Please release an updated build of the app, it’s been an entire year.

**Comment by dgies** [comment]
Confirmed on iPhone 14Pro with 17.2.  Can workaround by disabling native player but it's worse.

_edit: Updating to iOS 17.3 fixes the issue._

**Comment by IMmmKI** [comment]
I can confirm the same issue. Turning off resolves the issue.

**Comment by iChristGit** [comment]
Confirmed as well with my iPhone 11 Pro, after latest update it crashes with the "native video player" option, without the option is runs fine!

**Comment by thornbill** [comment]
There really is no need for additional confirmation here. You can use the thumbs up reaction on the original issue post and subscribe for updates so you get notified if any progress is made if you like. I am the main developer of the app and have already commented that I can replicate the issue on my phone. 👍

**Comment by Bittorn** [comment]
I also encountered this error on iOS 17.2, however this issue seems to have resolved itself on iOS 17.3.
I am running Jellyfin 10.8.10 (Expo 43.0.0) on an iPhone 13 with the native video player enabled and prefer fMP4 in HLS.

**Comment by thornbill** [comment]
Closing since this was fixed by updating to iOS 17.3.
