### ISSUE TITLE
Not all of my content is uploading

### ISSUE THREAD

**Issue by JellyFilledPi** [jellyfin/jellyfin-ios#477]
I set up my Jellyfin server, which is currently running off of my Raspberry Pi. My intent is to use my Jellyfin as a server to both stream LiveTV from an HDHomeRun and as a media server for my personal photos and videos. 

I have an external hard drive connected to my Pi. I generated my library under the “photos” library type. When I added the library to my server, not all of my media is showing up. As an example, one of my folders within this library is labeled as “Punta Cana Trip”. I renamed each photo and video within the folder with its own name, in order to ensure there are no duplicate names. So the names are in the format of “Punta_Cana - 1” “Punta_Cana - 2” etc. I labeled them in this manner, with the space, dash, space method, after the original formatting produced the same results. 

So again, the issue is that not all of media is being uploaded to the server. So this folder in particular should have over 300 videos/photos, but only approximately 180 actually uploaded. Ironically, many of the media types that are not uploading are photos. It appears that most of the video files uploaded correctly. 

I’m not sure if there other things I should try to solve this. 

Version: 10.8.13
Operating System: Linux
Architecture: Arm64

Thank you

**Comment by thornbill** [comment]
Please see https://jellyfin.org/docs/general/getting-help for help with troubleshooting your issue.

**Comment by JellyFilledPi** [comment]
I'm very confused on how I am supposed to obtain help. The Jellyfin website directed me to this forum page.

**Comment by thornbill** [comment]
The link I provided links to the community standards and to the [contact page](https://jellyfin.org/contact) where you can find support in our matrix and discord chat or on our forum.
