### ISSUE TITLE
IOS Jellyfin app stops playing V10.9 server

### ISSUE THREAD

**Issue by Adz5557** [jellyfin/jellyfin-ios#486]
Since updating Jellyfin server to V10.9 the IOS app for Jellyfin stops playing music as soon as the screen locks, or when moving to a different app on phone.

Previous to V10.9 this never happened. Other IOS apps for Jellyfin don’t exhibit this behaviour.

**Comment by ItzzCode** [comment]
Can confirm this happens on my device using the Jellyfin iOS app (it also appears to happen in the browser too?).

Extra info I just figured out:
When viewing the active devices tab on the dashboard (`domain/web/index.html#/dashboard/devices`), it shows that playback continues(???) while the client on the iOS device is in the background. Resuming then causes a weird stuttering to affect the current audio. When it stops audio is no longer audible without a refresh/close-reopen.

Screen capture from my phone: https://github.com/jellyfin/jellyfin-web/assets/51547168/7e6d08c0-7a0d-4b01-81b9-e78d62139f2e

**Comment by ItzzCode** [comment]
It happens too on iPadOS 17.3.1, using Safari. So it is **not exclusive to the app** or iOS/iPhones. I’ll update my comment to confirm if it happens on iOS web too.

**Comment by mkhasson97** [comment]
Same issue here

**Comment by bhart6397** [comment]
Can confirm, this issue still exists. Tested with the official Jellyfin app, safari browser and chrome browser.

**Comment by mkhasson97** [comment]
> Can confirm, this issue still exists. Tested with the official Jellyfin app, safari browser and chrome browser. It's not something inherently wrong with the app itself, it seems to be something to do with the way IOS puts apps in the background

No, the developers needs to enable the background mode within the app itself, because by default any running sound file will not work automatically when you run the app in the background

**Comment by eldemcan** [comment]
this is such a quantisential  feature, I hope resolve this quickly

**Comment by thornbill** [comment]
Duplicate of #19
