### ISSUE TITLE
"Jellyfin wants to access your Fitness data" - what?

### ISSUE THREAD

**Issue by bitfl0wer** [jellyfin/jellyfin-ios#491]
![image](https://github.com/jellyfin/jellyfin-expo/assets/39242991/fbdb8904-aa24-4277-9861-a06c1adb9bed)

I just got this notification on my iOS Jellyfin App (v1.5.0). Of course, I declined. Why would Jellyfin need to access fitness data? 🤔

**Comment by thornbill** [comment]
We haven't pushed an update to this app in ages... I suspect that something has changed in recent iOS updates that causes this prompt since we are using the screen orientation.

At least that's my guess. But of course no data is collected by the app and certainly not fitness data. 🤣

**Comment by isvein** [comment]
Same here.
Tried to reinstall jellyfin due to playback issues and it asks for access to the same thing.

Ios 17.5.1

**Comment by Dennis-Do** [comment]
So, maybe it's time to prepare an update as maybe with the right permissions background playback is working again. A lot of maybies but the hope dies last.

**Comment by thornbill** [comment]
This should be fixed by the changes to our build process for the 1.6.0 release.
