### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-ios#5]
The app is currently using the largest icon I could find which is 512x512. iOS requires a 1024x1024 app icon. 

Refs: https://docs.expo.io/versions/v34.0.0/guides/app-icons/#ios

**Comment by anthonylavado** [comment]
The icon is available here: [LargeIcon1024](https://user-images.githubusercontent.com/596194/64936897-27d2e400-d826-11e9-97a7-20e53d724073.png)
