### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Jamar84** [jellyfin/jellyfin-ios#508]
I have been trying to reset my password for Jellyfin but when I send off the request it doesn’t go to my email associated with my account.  So I can’t receive the link or PIN number to reset my password.  What should I do?

**Comment by anthonylavado** [comment]
Sorry friend, you might be a bit confused. Jellyfin is a server program that you run on your own computer, with your own media. We don't run any services, sell accounts, or anything like that.

If you're not running it yourself, then you'll want to speak with whoever _is_ running your Jellyfin server.
