### ISSUE TITLE
Orientation feature when playing video on avoid tv

### ISSUE THREAD

**Issue by hashtavia** [jellyfin/jellyfin-ios#511]
**Describe the feature**

Using jellyfin on android tv: videos are played in wrong orientation. 90 degree tilted, while on mobile the videos are are getting played correctly.

any solution for it?

**Additional context**

**Comment by hashtavia** [comment]
Additional info: videos are 1080p and 4k videos shot on various mobile phones.

**Comment by thornbill** [comment]
This repo is for the iOS app only.
