### ISSUE TITLE
Pelicula en mal archivo ( COCO)

### ISSUE THREAD

**Issue by davidfeno** [jellyfin/jellyfin-ios#519]
Formato de película erroneo , hay un formato en la pelicula exactamente la de coco que se ve partida como si de un formato para vr se tratara espero que se solucione pronto y se pueda disfrutar de la misma pelicula gracias y buen dia

**Comment by thornbill** [comment]
It seems like you are having trouble playing a specific movie. You should review our documentation on getting support: https://jellyfin.org/docs/general/getting-help
