### ISSUE TITLE
Subtitles get reset when when going to the next episode

### ISSUE THREAD

**Issue by Insprill** [jellyfin/jellyfin-ios#523]
**Describe the bug**
When the next episode of a show starts playing, the selected subtitles get reset without being reflected in the UI. The only way to get the intended subtitles back is to switch away from then back to the intended subtitles.

This makes watching most anime quite annoying, as the first English subtitle track tends not to include dialog, so every episode I have to switch subtitles off and back on.

I'm not able to reproduce this behaviour in desktop Firefox.

**System (please complete the following information):**
 - iOS Version: 16.7.10
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: 10.9.9

**To Reproduce**
1. Set subtitles to always play, and always to be burned in (unsure if relevant).
2. Find a show with two different subtitle languages.
3. Start playing an episode and switch the subtitles to a different language from the default.
4. Skip to the next episode.
5. The subtitles shown will be the default, although the one you last selected is still selected in the UI.

**Expected behavior**
The selected subtitles should properly persist between episodes as long as they still exist. Otherwise, the UI should update to reflect the currently showing subtitles.

**Comment by viown** [comment]
Hey, this issue was fixed in 10.10 https://github.com/jellyfin/jellyfin-web/pull/6112
