### ISSUE TITLE
LiveTV stops playing after 15 mins 

### ISSUE THREAD

**Issue by Misspower5** [jellyfin/jellyfin-ios#524]
First time using the site and livetv is a nightmare! After exactly 15 minutes the show cuts off and goes black. I have to back out of channel and then hit the play button again. Happens whether I’m using app or watching on safari.

**System (please complete the following information):**
 - iOS Version: 17.0
 - Jellyfin Expo version: newest downloaded today
 - Jellyfin Server version: freya.mvids.org

**To Reproduce**

1. Go to '...'. REELZ channel 
2. Tap on '....' On Patrol Live
3. Click play button 
4. Wait 15 mins and black screen, show stops

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thornbill** [comment]
It seems you might be looking for a service you have subscribed to... that has nothing to do with the Jellyfin project or this app.
