### ISSUE TITLE
Add mTLS client certificate support

### ISSUE THREAD

**Issue by michi7801** [jellyfin/jellyfin-ios#531]
It would be awesome if the app had support for mTLS client certificates through some sort of certificate import feature. This would mitigate (widely known) security issues with exposing Jellyfin to the Internet without a VPN. 

This would need no extra server-side code since mTLS is typically terminated at a reverse-proxy. It also "just-works" in the web since the browser is handling mTLS auth automatically.

**Additional context**
Similar functionality has been implemented in Immich (https://github.com/immich-app/immich/discussions/1611) and Nextcloud. Bitwarden also has active discussions to implement this feature.

**Comment by thornbill** [comment]
The expo framework that we use for this app does not allow us to make a change of this nature. Messing with how trusted networks are handled seems like a really easy way to introduce very bad bugs also so I would not be very interested in supporting this anyway.
