### ISSUE TITLE
I can sign into media trunk but not Jellyfin 

### ISSUE THREAD

**Issue by Bigdoggs66** [jellyfin/jellyfin-ios#532]
Everyone I try signing into Jellyfin, it dare Acess not authorize, see administrator. I don’t know why or how to fix. I’m update , I was watching tv on it last night, n it acted up, signed me out, n have t bee. Able to sign. Back in, n no ones helping me. Frank , BigDoggs66@gmail.com, thx u

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers
