### ISSUE TITLE
Logiing in issues 

### ISSUE THREAD

**Issue by GoodVibez937** [jellyfin/jellyfin-ios#533]
When logging in it says I’m not authorized for the server. It was doing fine this morning and now nada. 

Using 10.9.11

**Comment by GoodVibez937** [comment]
![IMG_3712](https://github.com/user-attachments/assets/bdb6efcf-b6af-40cd-8704-9f829f2fdef7)

**Comment by Bigdoggs66** [comment]
Same here.same issue. Was on it last night, boom it like kick me out, I can sign into media trunk not Jellyfin, n no ones seems to know anything or can help, as have no tech no how.  Never had issue before yes, now I get same message as you.

**Comment by Bigdoggs66** [comment]
![IMG_1110](https://github.com/user-attachments/assets/ff79b14a-6c10-4676-b26c-e47e521e7cf8)

**Comment by GoodVibez937** [comment]
Hmmmmm that’s interesting

**Comment by GoodVibez937** [comment]
Figured it out. Find the discord and it will help you.

**Comment by LHD658** [comment]
I have the same issue.. what is the discord? 

How do I fix this please?

**Comment by GoodVibez937** [comment]
On Oct 3, 2024, at 3:56 AM, LHD658 ***@***.***> wrote:﻿
I have the same issue.. what is the discord?
How do I fix this please?

**Comment by Bigdoggs66** [comment]
What’s it name se as here Sent from my iPhoneOn Oct 1, 2024, at 8:00 PM, GoodVibez937 ***@***.***> wrote:﻿
Figured it out. Find the discord and it will help you.

**Comment by Bigdoggs66** [comment]
I can’t find u on discord. My name is DJBigdoggs, can u request me, I’d really appreciate your help, I still can’t login on n been days since I watch movie or show.

**Comment by LHD658** [comment]
Hi,

That’s because I have no idea what discord is! 

I’m in now, I’m linked through mobile vids and just reset the server password and was able to regain access to Jellyfin.

**Comment by Bigdoggs66** [comment]
What server password.  U mean ur password for mobilevids of media trunk?   I just reset password n relinked on mobilevids.org n north same notice

**Comment by Bigdoggs66** [comment]
Thank u my friend. I’m back in, I appreciate your help, thank u very much Goodvibes and   Especially LHD658  for the detailed screenshots, ur the best my friend 🤘🏻

**Comment by LHD658** [comment]
You’re welcome!

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers
