### ISSUE TITLE
Can’t login to server

### ISSUE THREAD

**Issue by Petejuri** [jellyfin/jellyfin-ios#534]
When I try to login to Jellyfin on any platform it tells me I do not have access to the server contact administrator 

**System (please complete the following information):**
 - iOS Version:
 - Jellyfin Expo version:
 - Jellyfin Server version:

**To Reproduce**

2. Tap on '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers
