### ISSUE TITLE
Jellyfin iOS Won't Remember Login Information When Switching Servers

### ISSUE THREAD

**Issue by macmini888** [jellyfin/jellyfin-ios#535]
**Describe the bug**
I have an outside URL for remote access and an IP address host address for local network access for my Jellyfin server, which I have saved in my server list in the Jellyfin iOS app. In the past when I would switch between the two, it would hold my login information. Now, it prompts me to log in every time even with the "Remember Me?" checkbox checked.

**System (please complete the following information):**
 - iOS Version: 18.0.1
 - Jellyfin Expo version: 43.0.0 (also listed are these numbers 1.5.0 (5.5.0.0))
 - Jellyfin Server version: 10.9.11

**To Reproduce**
1. Have two servers stored in Jellyfin iOS
2. Select 1st server address and log in
3. Switch to 2nd server address and log in
4. Switch back to 1st server address... Log in information not saved. Prompted for login.

**Expected behavior**
The log in information holds across the different logins.

**Comment by gummykage** [comment]
Server since 10.0.x started happening.

**Comment by thornbill** [comment]
Why are you running a version that is almost 6 years old??? That is definitely not supported...

**Comment by thornbill** [comment]
I have been unable to replicate this issue.
