### ISSUE TITLE
Live tv

### ISSUE THREAD

**Issue by montague974** [jellyfin/jellyfin-ios#536]
**Describe the bug**

**System (please complete the following information):**
 - iOS Version:
 - Jellyfin Expo version:
 - Jellyfin Server version:

**To Reproduce**

2. Tap on '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by montague974** [comment]
There’s no live tv

**Comment by montague974** [comment]
No guide or channels

**Comment by thornbill** [comment]
Please complete the issue template properly.
