### ISSUE TITLE
Icons not working on iOS in Lockdown Mode

### ISSUE THREAD

**Issue by 0xThiebaut** [jellyfin/jellyfin-ios#537]
**Describe the bug**
On iOS devices with Lockdown Mode enabled, icons do not render.

**System (please complete the following information):**
 - iOS Version: 18.0.1
 - Jellyfin Expo version: 43.0.0
 - Jellyfin Server version: 10.9.11

**To Reproduce**
1. [Enable Lockdown Mode](https://support.apple.com/en-us/105120)
2. Open the Jellyfin iOS application

**Expected behavior**
Jellyfin should not be impacted by Lockdown Mode.

**Screenshots**
![image](https://github.com/user-attachments/assets/4dfc889d-38ee-4c94-9ecd-dd3d09c8e97e)

![image](https://github.com/user-attachments/assets/ca537f0d-89da-45ac-b620-d3a9d574f9de)

**Comment by thornbill** [comment]
> Web browsing - Certain complex web technologies are blocked, which might cause some websites to load more slowly or not operate correctly. In addition, **web fonts might not be displayed**, and images might be replaced with a missing image icon.

Sounds like this is expected behavior. Those icons are part of an icon font loaded from the Jellyfin server.

**Comment by 0xThiebaut** [comment]
Thanks! Would have expected these to be embedded in the application. If this is indeed intended behaviour, we can close this issue.

**Comment by thornbill** [comment]
Closing as this is expected for now. It might work better in the future as the icons move to SVG instead of using an icon font, but that will be a long term change in jellyfin-web.
