### ISSUE TITLE
No playback on iPad

### ISSUE THREAD

**Issue by grigsby** [jellyfin/jellyfin-ios#55]
Jellyfin client on iPad Pro 9.7-inch, iOS 13.3.1. The app launches, and I can browse my libraries, but playing any media only gives a black screen and no audio. The media controls are available on screen and the location mark is moving forward, but the media is not visible or audible.

**Comment by anthonylavado** [comment]
Does the media work if you just access the web interface with Safari?

**Comment by grigsby** [comment]
No, opening in Safari displays the same behavior. Everything seems like it should be working -- the on-screen controls are showing and interactive, scrubbing works and even shows video thumbnail chapter previews, subtitles are displayed, etc. But the media player is black/blank and there is no audio.

**Comment by anthonylavado** [comment]
@grigsby Ah okay. We are essentially using a web view, so if it doesn’t work in Safari, it won’t work here.

We’ll need to figure out _why_ it isn’t working for you first. Do you have transcoding enabled for your user? Does music work? (You can try with a small mp3 or m4a.)

**Comment by grigsby** [comment]
Hmm. Looks like it's probably a server-side issue. I thought it had been working on other client platforms, but now I'm getting the same results on all of my devices and browsers. Let me do some troubleshooting and I'll update this thread when I figure out what's going on. Might not be a client issue at all. Thank you for the help!

**Comment by grigsby** [comment]
Ok, it was a problem with my docker installation. I think it was a permissions problem with the transcoding directory. But it's sorted out now and jellyfin on the iPad is working great! Sorry for taking up your time with this. Thank you so much for your help and for building a jellyfin client!

**Comment by thornbill** [comment]
Glad you got it working!

**Comment by SenorSmartyPants** [comment]
What did you do specifically to fix this? I have the same issue on my iOS device.

**Comment by grigsby** [comment]
I think the problem was that my docker container was running as the wrong user, so it was having trouble reading/writing the transcoding directory. I was seeing errors in the logs about not being able to read files in the transcoding directory. At least, I think that was part of the problem, since I also changed a couple other things at the same time. I'm also trying to decide whether to use the linuxserver.io docker image or the jellyfin image.
