### ISSUE TITLE
You are not authorized to access the server.

### ISSUE THREAD

**Issue by Tbyeah11** [jellyfin/jellyfin-ios#552]
I’m having login problems on Jellyfin Thor.mvids.org. I keep forgetting “ You are not authorized to access the server at this time. Please contact your server administrator for more information”. How do I fix this and contact my server administrator? Someone please help. Thank you

**Comment by Showman305** [comment]
I am having the same issue

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers
