### ISSUE TITLE
Unable to lock into my account

### ISSUE THREAD

**Issue by antz1701** [jellyfin/jellyfin-ios#553]
**Describe the bug**

**System (please complete the following information):**
 - iOS Version:
 - Jellyfin Expo version:
 - Jellyfin Server version:

**To Reproduce**

2. Tap on '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers

**Comment by antz1701** [comment]
Hi there! Can you verify my account ***@***.*** is active. My November bill was not deducted, therefore l unable to open my Jellyfin account. Kindly advice. Thank you


Sent from Yahoo Mail for iPad


On Sunday, November 10, 2024, 10:44 PM, Bill Thornton ***@***.***> wrote:




Closed #553 as not planned.

**Comment by thornbill** [comment]
Did you read the link I posted???? Jellyfin is an open source project it has no affiliation with whatever you are paying for. Contact whoever you are paying if you are having issues.
