### ISSUE TITLE
iPad(iOS 10.3.3) issues with connecting

### ISSUE THREAD

**Issue by Smdytb1** [jellyfin/jellyfin-ios#56]
![image](https://user-images.githubusercontent.com/13372034/76221423-6fdc2d80-61ef-11ea-81d1-37f2b514ed98.png)
when connecting to a server, this pops up after a full factory reset. it did not do this before.
safari logs in just fine but broke due to an update. this app is the only thing that allows me to watch jellyfin at the moment.

**Comment by thornbill** [comment]
This is a really strange error. That message is coming from the webapp, so it _is_ connecting to the server successfully, but for some reason the webapp thinks Jellyfin is unavailable. Could you provide some additional details about how you are running the server (which OS, are you using docker, is it behind a reverse proxy) and what version you are running? Also are you able to connect using a web browser on the iPad and other systems?

**Comment by Smdytb1** [comment]
> 
> 
> This is a really strange error. That message is coming from the webapp, so it _is_ connecting to the server successfully, but for some reason the webapp thinks Jellyfin is unavailable. Could you provide some additional details about how you are running the server (which OS, are you using docker, is it behind a reverse proxy) and what version you are running? Also are you able to connect using a web browser on the iPad and other systems?

Ubuntu 18.04 lts, Docker, reverse proxy, using traefik reverse proxy and the linuxserver container build.
I am able to connect but not play video on browsers and other devices. Tried various browsers on iPad with no luck, chrome is no longer supported on 10.3.3 nor firefox. streaming video works on desktop though, but only direct. 

the base url is / and not /jellyfin but im not managing this interface since I have no access to it

**Comment by anthonylavado** [comment]
@Smdytb1 A thought just occurred to me - right now, the app uses a Web view, so if you can't log in with Safari, this app won't work either.

**Edit** - I see you said you could log in with Safari, but it's broken? What's not working at the moment?

**Comment by PelvisBass** [comment]
I have this same issue on an ipad4 (ios 10.3.4). I type in the correct IP then log in with my username and password but after I do that I get that same error screen as the first post and am unable to continue with the app. When using safari however I get a bit further and can choose a video to play but then I get this error.
![V87o5jX](https://user-images.githubusercontent.com/48794791/76670396-ab1b8b00-6566-11ea-941e-7f3b62e2699b.png)

**Comment by studioai** [comment]
The same on iOS 10.3.4(iPhone 5)
I could logged in on safari and chrome (desktop)
I am using Nginx for reverse proxy.
However, the result was same I tried 
to connect on my local address without reverse proxy.

**Comment by Smdytb1** [comment]
Has there been any update to this???

**Comment by dkanada** [comment]
@Smdytb1 we would need some browser logs to be honest, since almost none of use use Apple devices so we can't test this issue.

**Comment by thornbill** [comment]
Well a few of us use iOS devices (myself being one of them), but we haven’t been able to replicate this issue. I’m guessing it may be something to do with how the proxy and/or Jellyfin’s network settings are configured.

**Comment by studioai** [comment]
The weirdest part of this is there is no log related trying to connect from the app on jellyfin server-side even if it has 'debug' log level.
I guess this issue completely due to the client(app).

**Comment by anthonylavado** [comment]
It might be an issue with Expo on older versions of iOS then.

**Comment by Smdytb1** [comment]
the thing is, it worked fine before. until a factory reset (iPad had to be wiped clean) and now its just showing the same error over and over... with no logs on the server-side to be seen. and no way to get logs off an apple product that I know of

**Comment by cbzehner** [comment]
Just to provide a data point, I just set up a fresh installation on iPadOS 13.3.1. After upgrading to 13.4 I was able to delete and re-add my local server from the app without issue.

**Comment by thornbill** [comment]
It looks like this can happen if the device name includes non-ascii characters which iOS does by default. For example the apostrophe in "Bill’s iPhone" is non-ascii. We should have a fix for this soon!

**Comment by studioai** [comment]
> It looks like this can happen if the device name includes non-ascii characters which iOS does by default. For example the apostrophe in "Bill’s iPhone" is non-ascii. We should have a fix for this soon!

I changed my device name by omitting the apostrophe and the issue's cleared!
