### ISSUE TITLE
Jellyfin is not letting me sign in, server not working please fix

### ISSUE THREAD

**Issue by Bluejays9293** [jellyfin/jellyfin-ios#563]
Jellyfin server not letting me sign in on my devices please fix, been a member since 2013 and would hate to cancel my subscription, this format change should be better 

Thanks Fred Fernandes

**Comment by thornbill** [comment]
You are undoubtedly paying for a piracy service that is not Jellyfin and is in no way affiliated with the Jellyfin open source project (that only started in 2018). Your issue is with whoever you are paying.

https://jellyfin.org/docs/general/community-standards/servers
