### ISSUE TITLE
Activity Filter/Search - Blank Entries

### ISSUE THREAD

**Issue by RedSoxFan04** [jellyfin/jellyfin-ios#575]
**Describe the bug**
When filtering activity logs, there are a lot of blank spaces. Sometimes, you have to skip through multiple blank pages - even when the app is set to show 100 entries per page - just to get to the next entries in the search results.

**System**
 - iOS Version: 15.8.3
 - Jellyfin Expo version: 1.5.0
 - Jellyfin Server version: 10.10

**To Reproduce**
1. Go to Dashboard _> Activity 
2. Tap on filter icon, enter search term(s) and tap expand button. 
3. Scroll down to the bottom of the page and use the arrows to keep advancing to the page.
4. See all of the blank spaces

**Expected behavior**
Filter/search results shown without blank entries/spaces.

**Comment by thornbill** [comment]
This is the expected behavior due to api limitations. See https://github.com/jellyfin/jellyfin-web/issues/6221.
