### ISSUE TITLE
I can’t reset my password on Jellyfin

### ISSUE THREAD

**Issue by rayct77** [jellyfin/jellyfin-ios#577]
When I click on “forgot password “ I get the following:

“The following file has been created on your server and contains instructions on how to proceed
Enter PIN here to finish Password Reset
/var/lib/jellyfin/passwordreset3940598e-c405-48e4-
a440-Obf15de42a78 json”

**System (please complete the following information):**
 - iOS Version: 18.1.1
 - Jellyfin Expo version:
 - Jellyfin Server version:

**To Reproduce**

2. Tap on '....'

**Expected behavior**
 I expected to receive an email to reset password or an explanation as to where I can find the link it produced 

**Screenshots**

**Additional context**

**Comment by viown** [comment]
Are you the server owner? You'll need to access your instance and get the PIN from that file.

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/community-standards/servers
