### ISSUE TITLE
When direct playing music, moving the app to the background neither pauses the music, nor outputs any sound

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-ios#585]
**Describe the bug**
When music is direct playing, moving the app to the background causes weird behavior

**System (please complete the following information):**
 - iOS Version: 18.1.1
 - Jellyfin Expo version: 1.5.0 (5.5.0.0)
 - Jellyfin Server version: 10.10.3

**To Reproduce**
1. Start playing a music file that direct plays. I used a MP3, a ALAC and a FLAC file and all of them produces the issue.
2. Move the app to background, you should hear the music stop
3. Open control center and see that music is not paused
4. Return to the app and the sound resumes at a future point in the music file

**Expected behavior**
The music should either continue playing or pause

**Screenshots**
https://github.com/user-attachments/assets/d2e9f964-f648-4cf8-9e2a-b3e5967b63ae

**Additional context**
Does not happen when it is transcoding

**Comment by thornbill** [comment]
Background playback of audio is not currently supported: https://github.com/jellyfin/jellyfin-expo/issues/19
