### ISSUE TITLE
When playing music, leaving the app and returning breaks the pause button

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-ios#586]
**Describe the bug**
When playing music, leaving the app and returning breaks the pause button

**System (please complete the following information):**
 - iOS Version: 18.1.1
 - Jellyfin Expo version: 1.5.0 (5.5.0.0)
 - Jellyfin Server version: 10.10.3

**To Reproduce**
1. Play music in the app
2. Leave the app so that it is in the background
3. Return to the app
4. Press pause
5. Hear error

**Expected behavior**
The music should pause immediately

**Screenshots**
https://github.com/user-attachments/assets/13200a4d-264c-4b37-84fd-8c24ead50ee9

**Additional context**
Happens both transcoding and direct playing

**Comment by thornbill** [comment]
Background playback of audio is not currently supported: https://github.com/jellyfin/jellyfin-expo/issues/19
