### ISSUE TITLE
When background playback is interrupted by another app, files that direct play won't output any sound until the web interface is reloaded

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-ios#587]
**Describe the bug**
As the title suggests

**System (please complete the following information):**
 - iOS Version: 18.1.1
 - Jellyfin Expo version: 1.5.0 (5.5.0.0)
 - Jellyfin Server version: 10.10.13

**To Reproduce**
1. Start playing music
2. Go to another app that plays media (I tried both Youtube and Finamp)
3. Start playing media in the other app. Playback from Expo should be interrupted
4. Return to expo
5. Play music that direct plays (can be a different track)
6. Hear no sound 

**Expected behavior**
Music should play

**Screenshots**
https://github.com/user-attachments/assets/203fc2a2-31bd-46b5-a8e9-1119a2c2ff3a

**Additional context**
Only happens with music that direct plays. Files that transcode work without issues. In my case I used a FLAC file

**Comment by thornbill** [comment]
Background playback of audio is not currently supported: https://github.com/jellyfin/jellyfin-expo/issues/19
