### ISSUE TITLE
Terrible lag/ loading

### ISSUE THREAD

**Issue by Beartrack23** [jellyfin/jellyfin-ios#594]
Shows lag/ load every couple seconds shows are unwatchable. Not sure what causes the problem, been doing it since i signed up and i just quit watching.

Then i tried to change mbits/sec and accidentally selected 1 mbits/sec and now cannot play any shows. Says user does not have access to this media

**Comment by thornbill** [comment]
Jellyfin is a **selfhosted** personal media server. If you are using a paying someone for access it is **NOT** us and we **CANNOT** provide support.

https://jellyfin.org/docs/general/community-standards/servers
