### ISSUE TITLE
iPad rotation issue

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-ios#74]
Hello, I have just updated to the latest version of the app: 1.1.1 and when opening the app in the landscape orientation it will automatically switch to portrait forcing the user to physically rotate the iPad again for it to switch back to landscape. This is especially problematic with rotation lock on.

Model: iPad Air 2
iOS: 13.3.1

**Comment by thornbill** [comment]
This is interesting. It _should_ only lock to portrait on phones.

https://github.com/jellyfin/jellyfin-expo/blob/master/App.js#L30-L33

Seems like the `isPad` property may be incorrect for that device.

**Comment by SwissOS** [comment]
Confirming this bug on iPad 2018 model with iOS 13.4.

Especially an issue when I have rotation lock on, then I need to turn it off first to get Jellyfin back to landscape mode. Quite annoying.

**Comment by genfuzuki** [comment]
Can I also add the fact that it will only rotate landscape on one axis on iPhone, If you rotate the phone 180 degrees it stays upside down. Not a major issue but I like to rotate clockwise so I can cup my Left hand around the speaker (To get a better sound direction). Thanks

**Comment by thornbill** [comment]
@danielp123 If you go to the Settings screen in the app at the bottom it lists the app version. Could you confirm what that is? I have tried to replicate this on a couple iPad generations (4th gen. on 10.3.3 and 7th gen. on 13.4.1) and haven't been able to reproduce the lock issue in the latest version of the app.

@genfuzuki I may just add an option to disable screen locking on the iPhone also. There was an issue where when we used the `LANDSCAPE` orientation lock, Jellyfin would rotate in the opposite direction of every other video app so we changed it to a specific landscape direction. This means you can no longer rotate to the other landscape direction unfortunately. It would be great if we could specify the default direction while allowing either, but that doesn't seem to be an option.

**Comment by emilytrau** [comment]
I’m consistently getting this issue on my iPad 7th Gen on iOS 13.4.1. The rotation fixes itself after exiting the app and returning from the home screen.

**Comment by anthonylavado** [comment]
@angustrau Which version of the app do you have installed? It should be at the bottom on the "Settings" screen.

**Comment by emilytrau** [comment]
@anthonylavado I have 
```
Jellyfin Mobile (iOS)
1.1.1 (1)
Expo Version: 37.0.0
```

**Comment by anthonylavado** [comment]
Building this to make a TestFlight install. I'll share a beta link soon.

**Comment by anthonylavado** [comment]
It's in review with Apple, once that passes I'll send the beta link along.

**Comment by emilytrau** [comment]
Looking forward to testing it 🙂

**Comment by anthonylavado** [comment]
So for reference, I did get this through to our internal TestFlight, but it seems the issue persists. We're gonna take another look at it.

**Comment by thornbill** [comment]
We did some testing and even with disabling all of our screen locking code the issue with iPads rotating to portrait was still present.

[This issue](https://github.com/expo/expo/issues/8210) from Expo seems to describe the issue we are having. Specifically this part:

> On initial, when phone is in the horizontal position, it is rotating by itself to the portrait

I think we are blocked until this issue is fixed upstream.

**Comment by andra5** [comment]
> 
> 
> It's in review with Apple, once that passes I'll send the beta link along.

can I get in on the TestFlight?

**Comment by Hukuma1** [comment]
Same issue here with iPad Air 2. Initially just switches orientation so I have to manually flip iPad. They mentioned https://github.com/expo/expo/issues/9131#issuecomment-657539687 that it's fixed in latest version.

**Comment by thornbill** [comment]
Right they have a fix in but it hasn’t made it into a published release yet.

https://github.com/expo/expo/blob/master/packages/expo-screen-orientation/CHANGELOG.md

**Comment by thornbill** [comment]
This is blocked until Expo 39 is released.

Refs: https://github.com/expo/expo/issues/10055

**Comment by bberenberg** [comment]
Seems to have re-occurred on Jellyfin 1.5.0 on iPad Pro (12.9-inch) (5th generation) Model number MHNK3LL/A with iPadOS 16.1.1 (20B101). Should this be filed as a new bug? Regression? Not sure how this project likes to operate.
