### ISSUE TITLE
Random Repeat

### ISSUE THREAD

**Issue by kellysholden** [jellyfin/jellyfin-ios#76]
Random portions of tv shows repeat, sometimes multiple times during normal playback. 

At one point, I couldn’t fast forward past a certain section and every time I tried manually dragging the slider, it would revert back to a singular spot. 

Checked file by playing infuse, and it played without problem.

**Comment by anthonylavado** [comment]
When you're watching a video that does this, can you check the dashboard from another device (like a computer)?

It should say whether the video is transcoding or not, and if it is, it should give a reason for why when you click on the "i" button.

**Comment by kellysholden** [comment]
I will try to repeat the situation tonight/tomorrow and check that.
