### ISSUE TITLE
iPad v.10.3.4 Movie Playback Error

### ISSUE THREAD

**Issue by Eemmiilly** [jellyfin/jellyfin-ios#78]
On servers that contain Movies or Series...unable to begin watching movies as i assume the Media player for this Ipad is not compatabile however when checking on the Admin Panel, the movie + movie runtime is shown even though nothing is shown on my side.

On my side though, all thats visible is a play button with an arrow through it diagonally, playlist (A-Z) and the Home and Settings below.

Same with Safari...opening links leads to a black screen with the URL. Saw this in another post but not sure if a definitive solution was found.There arent any issues with connection or the app itself. Music plays too without any hiccups. Just looking for a solution or troubleshooting method for my querry.

Thanks.

**Comment by anthonylavado** [comment]
Is the iPad on iOS 10.3.4?

**Comment by Eemmiilly** [comment]
> Is the iPad on iOS 10.3.4?

Yes. Thats the 'latest' version. No software update in about a year as i assume Apple doesnt support this model.

**Comment by ajlowndes** [comment]
Mine is on 10.3.3 and doing the same thing.

**Comment by anthonylavado** [comment]
With the next release of this app, the lowest supported version of iOS will be 12 and newer. If you still need to use iOS 10, I would recommend trying VLC which should still support as far back as iOS 9.

If your Jellyfin server is on your local network, Jellyfin will appear as a file server under the "Network" tab, and will play movies over DLNA.
