### ISSUE TITLE
"Could not connect to server error" with Apache VirtualHost configuration on port 8443 

### ISSUE THREAD

**Issue by rvilarl** [jellyfin/jellyfin-ios#79]
The configuration works on browser but not on the app.
I have configured a user test with password test for your convenience on
https://michaelecke.com:8443
I canot use https://michaelecke.com because I have a photography web there.

Thanks a lot for the support!!

Configuration on Apache:

<VirtualHost *:8443>
  ServerName michaelecke.com
  ProxyPreserveHost On
  ProxyPass "/socket" "ws://localhost:8096/socket"
  ProxyPassReverse "/socket" "ws://localhost:8096/socket"
  ProxyPass "/" "http://localhost:8096/"
  ProxyPassReverse "/" "http://localhost:8096/"
  SSLEngine on
  SSLCertificateFile /etc/httpd/namecheap/michaelecke_com.crt
  SSLCertificateKeyFile /etc/httpd/namecheap/server.key
  Protocols h2 http/1.1
  SSLCipherSuite HIGH:RC4-SHA:AES128-SHA:!aNULL:!MD5
  SSLHonorCipherOrder on
  SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
  ErrorLog "/var/log/httpd/michaelecke.com.8443_error_log"
  CustomLog "/var/log/httpd/michaelecke.com.8443_access_log" combined
</VirtualHost>

**Comment by thornbill** [comment]
It looks like the issue is due to the `/system/info/public` endpoint returning a 502 HTTP status for some reason. The app checks this to verify it's connecting to a Jellyfin server and not some random website. I don't see anything offhand with your config that would interfere with that though.

**Comment by rvilarl** [comment]
Could you provide a hint? The file system/info/public is not in the server and I am indeed using a proxy with apache. What shoud be the content of this file?
By the way I get the same error with caddy.
Thanks again.

**Comment by rvilarl** [comment]
I have been readin on the topic and I have solved the problem.
With a proxy in admin | advanced | networking, the option "bind to local network address" have to be configured with 127.0.0.1.

Thanks a lot for your quick support!

Have a look at the fotos, perhaps you like them ;)

**Comment by thornbill** [comment]
Great! Glad you were able to figure it out. I had asked around if anyone saw anything off in your config since it seemed to match the docs, but hadn’t heard anything. Seems that part was all good anyway!
