### ISSUE TITLE
Album info does not show on lock screen.

### ISSUE THREAD

**Issue by Bitwolfies** [jellyfin/jellyfin-ios#87]
![unnamed](https://user-images.githubusercontent.com/65789901/85078648-65e5a580-b1b4-11ea-9a74-24fe91f1a3b8.png)
As seen here, when playing a song while my phone is locked/looking at the music tab in control center, there's zero artwork or info.

**Comment by Bitwolfies** [comment]
Also strangely a known issue is that on ios music does not play in the background, but mine does just fine, even when my screen is locked.

**Comment by thornbill** [comment]
@Darkwolf1515 what iOS version are you on? Background playback worked better for me in older iOS versions. It would at least finish the currently playing song.

**Comment by Bitwolfies** [comment]
13.5.1, just saw that background playback was supposedly broken and I thought it was worth mentioning, I do wonder why song data doesn’t show up though

**Comment by ghost** [comment]
Can't wait for this to be implemented! Another thing to note that, as a result of this, forwarding and going back in the control/notification center also doesn't work.

**Comment by thornbill** [comment]
I’m tagging this as blocked since it will require ejecting to React Native.

**Comment by Bitwolfies** [comment]
So uh, this works now, I dunno if you added it, but it works.

**Comment by anthonylavado** [comment]
We definitely didn't do anything special for this. What a pleasant surprise from iOS 15 😂

**Comment by thornbill** [comment]
Now if they would just fix background playback again... 🤣

**Comment by thornbill** [comment]
Closing this because it appears to have been added in iOS 15! 🎉
