### ISSUE TITLE
[IOS] Audio streaming stops when device enters on sleep mode

### ISSUE THREAD

**Issue by hardwareadictos** [jellyfin/jellyfin-ios#94]
Hey! Good morning all.

Just want to report that when i'm streaming audio on my IPad 2018, when the device screen goes of and the ipad starts sleeping the media stream (music mainly, because when video is streamed, device doesn't go to sleep) gets stopped. I have to unlock the IPad, pause the stream and resume it to force it work again.

Feel free to ask for whatever information you need.

Cheers :)

**Comment by anthonylavado** [comment]
Okay, I have moved this to the correct repository. We are aware of the issue, it is in #19
